server:
  port: 10011

  tomcat:
    max-http-header-size: 8192


logging:
  file: logs/spring-boot-logging.log
  level:
    com.xlkj.website: info
#    org:
#      springframework:
#        security: info

system.path:
  basePath: D:\\app/files    # 所有文件根目录
  activity : activity
  picture: picture
  voice: voice
  app: app
  server-address: 127.0.0.1 #附件下载地址




spring:
#  profiles:
#    include: datasource,mybatis
  redis:
    database: 0
    timeout: 0
      # Redis服务器地址
    host: 192.168.3.253
      # Redis服务器连接端口
    port: 6379
      # Redis服务器连接密码（默认为空）
    password: 123456
      # 连接池最大连接数（使用负值表示没有限制）
    pool:
    max-active: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
        # 连接池中的最大空闲连接
    max-idle: -1
        # 连接池中的最小空闲连接
    min-idle: 0



  datasource:
    url: jdbc:mysql://59.110.226.188:3306/xlkj_website?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver



#  http:
#      multipart:
#        max-file-size: 100MB   #单个
#        max-request-size: 500MB   #总共

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xlkj.website.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL语句控制台打印



#  user:
#    name: admin
#    password: 123456




















